### PR TITLE
Added a Dark-theme mode compatibility for the website.

### PR DESCRIPTION
**Pull request by Nagasandesh**
Added a new JavaScript file Dark_theme.js , modified the html , css  styles,  changed the app_icon style.

### CODE REVIEW

**Comment by ostheperson** [comment]
nice 👍

**Comment by Nagasandesh** [comment]
Hey @OS-the-Person thanks. Please Can you add Hacktoberfest accepted label to my contribution so that it will be a great help to my work

**Comment by ostheperson** [comment]
no problem

**Comment by Nagasandesh** [comment]
Thanks..

**Pull request merged**
